/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/office.glb 
*/

import React from "react"
import { useGraph } from "@react-three/fiber"
import { useGLTF } from "@react-three/drei"
import { SkeletonUtils } from "three-stdlib"

export function Office(props) {
  const { scene } = useGLTF("models/office.glb")
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} />
      <mesh
        geometry={nodes.s4studio_mesh_0.geometry}
        material={materials.DIFFUSE}
      />
      <mesh
        geometry={nodes.s4studio_mesh_0001.geometry}
        material={materials["DIFFUSE.001"]}
      />
      <mesh
        geometry={nodes.s4studio_mesh_0002.geometry}
        material={materials["DIFFUSE.003"]}
      />
      <mesh
        geometry={nodes.s4studio_mesh_1002.geometry}
        material={materials["DIFFUSE.004"]}
      />
      <mesh
        geometry={nodes.s4studio_mesh_2.geometry}
        material={materials["DIFFUSE.005"]}
      />
      <mesh
        geometry={nodes.s4studio_mesh_3.geometry}
        material={materials["DIFFUSE.008"]}
      />
      <mesh
        geometry={nodes.s4studio_mesh_3001.geometry}
        material={materials["DIFFUSE.011"]}
      />
      <mesh
        geometry={nodes.s4studio_mesh_0004.geometry}
        material={materials["DIFFUSE.012"]}
      />
      <mesh
        geometry={nodes.s4studio_mesh_1005.geometry}
        material={materials["DIFFUSE.013"]}
      />
      <mesh
        geometry={nodes.s4studio_mesh_0005.geometry}
        material={materials["DIFFUSE.014"]}
      />
      <mesh
        geometry={nodes.s4studio_mesh_1006.geometry}
        material={materials["DIFFUSE.015"]}
      />
      <mesh
        geometry={nodes.s4studio_mesh_0006.geometry}
        material={materials["DIFFUSE.016"]}
      />
      <mesh
        geometry={nodes.s4studio_mesh_1007.geometry}
        material={materials["DIFFUSE.017"]}
      />
      <mesh
        geometry={nodes.s4studio_mesh_0007.geometry}
        material={materials["DIFFUSE.018"]}
      />
      <mesh
        geometry={nodes.s4studio_mesh_1008.geometry}
        material={materials["DIFFUSE.019"]}
      />
      <mesh
        geometry={nodes.s4studio_mesh_0008.geometry}
        material={materials["DIFFUSE.020"]}
      />
      <skinnedMesh
        geometry={nodes.s4studio_mesh_1.geometry}
        material={materials.DIFFUSE}
        skeleton={nodes.s4studio_mesh_1.skeleton}
      />
      <skinnedMesh
        geometry={nodes.s4studio_mesh_1001.geometry}
        material={materials["DIFFUSE.002"]}
        skeleton={nodes.s4studio_mesh_1001.skeleton}
      />
      <skinnedMesh
        geometry={nodes.s4studio_mesh_1003.geometry}
        material={materials["DIFFUSE.007"]}
        skeleton={nodes.s4studio_mesh_1003.skeleton}
      />
      <skinnedMesh
        geometry={nodes.s4studio_mesh_0003.geometry}
        material={materials["DIFFUSE.009"]}
        skeleton={nodes.s4studio_mesh_0003.skeleton}
      />
      <skinnedMesh
        geometry={nodes.s4studio_mesh_1004.geometry}
        material={materials["DIFFUSE.010"]}
        skeleton={nodes.s4studio_mesh_1004.skeleton}
      />
      <skinnedMesh
        geometry={nodes.s4studio_mesh_2001.geometry}
        material={nodes.s4studio_mesh_2001.material}
        skeleton={nodes.s4studio_mesh_2001.skeleton}
      />
      <skinnedMesh
        geometry={nodes.s4studio_mesh_1009.geometry}
        material={materials["DIFFUSE.021"]}
        skeleton={nodes.s4studio_mesh_1009.skeleton}
      />
      <skinnedMesh
        geometry={nodes.s4studio_mesh_1010.geometry}
        material={materials["DIFFUSE.023"]}
        skeleton={nodes.s4studio_mesh_1010.skeleton}
      />
      <primitive object={nodes.b__ROOT__} />
      <primitive object={nodes.neutral_bone} />
      <primitive object={nodes.b__ROOT___1} />
      <primitive object={nodes.neutral_bone_1} />
      <primitive object={nodes.computerDesktop_rig} />
      <primitive object={nodes.neutral_bone_2} />
      <primitive object={nodes.computerDesktop_rig_1} />
      <primitive object={nodes.neutral_bone_3} />
      <primitive object={nodes.b__ROOT___6} />
      <primitive object={nodes.neutral_bone_4} />
      <primitive object={nodes.b__ROOT___7} />
    </group>
  )
}

useGLTF.preload("models/office.glb")
