/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/pleasework2.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/pleasework2.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.spine} />
      <primitive object={nodes.root} />
      <primitive object={nodes['MCH-torsoparent']} />
      <primitive object={nodes['MCH-hand_ikparentL']} />
      <primitive object={nodes['MCH-upper_arm_ik_targetparentL']} />
      <primitive object={nodes['MCH-hand_ikparentR']} />
      <primitive object={nodes['MCH-upper_arm_ik_targetparentR']} />
      <primitive object={nodes['MCH-foot_ikparentL']} />
      <primitive object={nodes['MCH-thigh_ik_targetparentL']} />
      <primitive object={nodes['MCH-foot_ikparentR']} />
      <primitive object={nodes['MCH-thigh_ik_targetparentR']} />
      <skinnedMesh geometry={nodes.model.geometry} material={materials['Material.001']} skeleton={nodes.model.skeleton}>
        <group position={[-0.096, 0.523, 0.264]} scale={7.45}>
          <mesh name="Tiny_Eye_1056" geometry={nodes.Tiny_Eye_1056.geometry} material={materials['Tiny Iris 1.3 (Cat Hazel Dilated)']} morphTargetDictionary={nodes.Tiny_Eye_1056.morphTargetDictionary} morphTargetInfluences={nodes.Tiny_Eye_1056.morphTargetInfluences} />
          <mesh name="Tiny_Eye_1056_1" geometry={nodes.Tiny_Eye_1056_1.geometry} material={materials['Tiny Sclera 1.3 (Cat Hazel Dilated)']} morphTargetDictionary={nodes.Tiny_Eye_1056_1.morphTargetDictionary} morphTargetInfluences={nodes.Tiny_Eye_1056_1.morphTargetInfluences} />
        </group>
        <group position={[0.09, 0.521, 0.269]} scale={7.45}>
          <mesh name="Tiny_Eye_1001" geometry={nodes.Tiny_Eye_1001.geometry} material={materials['Tiny Iris 1.3 (Cat Hazel Dilated).001']} morphTargetDictionary={nodes.Tiny_Eye_1001.morphTargetDictionary} morphTargetInfluences={nodes.Tiny_Eye_1001.morphTargetInfluences} />
          <mesh name="Tiny_Eye_1001_1" geometry={nodes.Tiny_Eye_1001_1.geometry} material={materials['Tiny Sclera 1.3 (Cat Hazel Dilated).001']} morphTargetDictionary={nodes.Tiny_Eye_1001_1.morphTargetDictionary} morphTargetInfluences={nodes.Tiny_Eye_1001_1.morphTargetInfluences} />
        </group>
      </skinnedMesh>
    </group>
  )
}

useGLTF.preload('/pleasework2.glb')
