/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/Bunny_Boy_Sips_Tea_1003091734.glb 
*/

import React from "react"
import { useGLTF } from "@react-three/drei"

export function BunnyBoy(props) {
  const { nodes, materials } = useGLTF(
    "models/Bunny_Boy_Sips_Tea_1003091734.glb"
  )
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload("models/Bunny_Boy_Sips_Tea_1003091734.glb")
